meta_product_name: "Koach & Co"
meta_title: "Koach & Co : vos séances de sport en plein air et à proximité"
meta_description: "Retrouvez votre coach sportif où, quand, et avec qui vous voulez sur des séances en plein air ! Votre abonnement de sport flexible et sans engagement."
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
